# Constants created by autoconf ./configure script
COREDPY_VERSION		= "4.8"
CORE_STATE_DIR		= "/var"
CORE_CONF_DIR		= "/etc/core"
CORE_DATA_DIR		= "/usr/share/core"
CORE_LIB_DIR		= "/usr/lib/core"
CORE_SBIN_DIR		= "/usr/sbin"

BRCTL_BIN               = "/usr/sbin/brctl"
IP_BIN                  = "/usr/sbin/ip"
TC_BIN                  = "/usr/sbin/tc"
EBTABLES_BIN            = "/usr/sbin/ebtables"
IFCONFIG_BIN            = "/usr/sbin/ifconfig"
NGCTL_BIN               = "no/ngctl"
VIMAGE_BIN              = "no/vimage"
QUAGGA_STATE_DIR        = "/var/run/quagga"
MOUNT_BIN               = "/usr/bin/mount"
UMOUNT_BIN              = "/usr/bin/umount"
